
const backendDomain= meta.env.VITE_APP_BACKEND_URL; //"http://localhost:8000";
const SummaryApi={
    SignUP:{
        url:`${backendDomain}/api/signup`,
        method:"POST"
    },
    Login:{
        url:`${backendDomain}/api/login`,
        method:"POST"
    },
    Current_user:{
        url:`${backendDomain}/api/user-details`,
        method:"GET"
    },
    logout_user:{
        url:`${backendDomain}/api/userLogout`,
        method:"GET"
    },
    allUser:{
        url:`${backendDomain}/api/all-user`,
        method:"GET"
    },
    updateUser:{
        url:`${backendDomain}/api/update-user`,
        method:"POST"
    },
    uploadProduct:{
        url:`${backendDomain}/api/upload-product`,
        method:"POST"
    },
    getAllProduct:{
        url:`${backendDomain}/api/all-product`,
        method:"GET"
    },
    findProduct:{
        url:`${backendDomain}/api/findProduct`,
        method:"GET"
    },
    updateProduct:{
        url:`${backendDomain}/api/update-product`,
        method:"POST"
    },
    getAllCategoryProduct:{
        url:`${backendDomain}/api/get-allcategoryproduct`,
        method:"GET"
    },
    getCategoryWiseProduct:{
        url:`${backendDomain}/api/get-categoryWiseProduct`,
        method:"POST"
    },
    getProductId:{
        url:`${backendDomain}/api/findproductid`,
        method:"POST"
    },
    getAddToCartProduct:{
        url:`${backendDomain}/api/addtocart`,
        method:"POST"
    },
    countAddToCartProduct:{
        url:`${backendDomain}/api/countaddtocartproduct`,
        method:"GET"
    },
    addToCartProductView:{
        url:`${backendDomain}/api/addtocartproductview`,
        method:"GET"
    },
    updateAddtoCartProduct:{
        url:`${backendDomain}/api/updateaddtocartproduct`,
        method:"POST"
    },
    removeProductFromAddToCart:{
        url:`${backendDomain}/api/removeProductFromAddToCart`,
        method:"POST"
    },
    serachFunctionality:{
        url:`${backendDomain}/api/search`,
        method:"GET"
    },
    filterProduct:{
        url:`${backendDomain}/api/filter-product`,
        method:"POST"
    },
    payment:{
        url:`${backendDomain}/api/checkout`,
        method:"POST"
    },
    getOrder:{
        url:`${backendDomain}/api/order-list`,
        method:"GET"
    }
}

export default SummaryApi